controllers/SiteController.php
<?php

namespace app\controllers;

use app\extensions\Controller;
use app\models\AuthKey;
use app\models\User;
use general\ext\api\auth\AuthApi;
use general\ext\api\auth\AuthUrlCreator;
use Yii;
use yii\filters\AccessControl;
use yii\web\Response;

class SiteController extends Controller {
    //public $defaultAction = 'login';
	//public $layout = 'empty';
	public function behaviors() {
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only' => ['index', 'rating', 'dialogs', 'logout', 'logout-everywhere'],
				'rules' => [
					[
						'actions' => ['index', 'rating', 'dialogs', 'logout', 'logout-everywhere'],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
		];
	}
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
	public function actionIndex() {
		$this->layout = 'empty';
		return $this->render('index');
	}
	/*public function actionRating() {
		return $this->render('rating');
	}
	public function actionDialogs() {
		return $this->render('dialogs');
	}*/

	/*public function actionSignup() {
		$model = new SignupForm();
		if ($model->load(Yii::$app->request->post())) {
			if ($user = $model->signup()) {
				if (Yii::$app->user->login($user, Yii::$app->params['durationAuth'])) {
					return $this->goHome();
				}
			}
		}

		return $this->render('signup', [
			'model' => $model,
		]);
	}*/

	public function actionSignup() {
		$this->layout = 'emptyHtml';
		return $this->render('signup');
	}

    public function actionLoginWithAuthKey($result) {
	    $this->layout = 'emptyHtml';
	    if($result == 'success') {
		    if (!Yii::$app->user->isGuest) {
			    return $this->render('redirect', ['url' => '/']);
		    }

		    $mark = Yii::$app->request->get('key');
		    if($key = AuthApi::userGetServiceAuthKey($mark)) {
			    $user = User::getFromAuth($key['user_id']);

			    $model = new AuthKey();
			    $model->auth_key = $key['auth_key'];
			    $model->browser = Yii::$app->request->userAgent;
			    $model->ip = Yii::$app->request->userIP;
			    $model->user_id = $key['user_id'];
			    $model->save();

			    if (Yii::$app->user->login($user, Yii::$app->params['durationAuth'])) {
				    return $this->render('refresh');
			    }
		    } else {
			    //@todo сделать вывод ошибки
		    }
	    }
	    return $this->render('redirect', ['url' => '/']);
    }
	public function actionLoginWithMark($mark) {
		if (!Yii::$app->user->isGuest) {
			return '';
		}

		\Yii::$app->response->format = Response::FORMAT_JSONP;
		if($key = AuthApi::userGetServiceAuthKey($mark)) {
			$user = User::getFromAuth($key['user_id']);

			$model = new AuthKey();
			$model->auth_key = $key['auth_key'];
			$model->browser = Yii::$app->request->userAgent;
			$model->ip = Yii::$app->request->userIP;
			$model->user_id = $key['user_id'];
			$model->save();

			if (Yii::$app->user->login($user, Yii::$app->params['durationAuth'])) {
				return [
					'data' => 'success',
					'callback' => 'loginWithMark',
				];
			}
		}
		return [
			'data' => 'error',
			'callback' => 'loginWithMark',
		];
	}
	public function actionLogin() {
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}
		$this->layout = 'emptyHtml';
		return $this->render('login');
	}
    public function actionLogout() {
        User::logout();
	    return $this->redirect(
		    AuthUrlCreator::userLogout(
			    Yii::$app->id,
			    '//' . Yii::$app->request->getServerName()));
    }
	public function actionLogoutEverywhere() {
		User::logoutEverywhere();
		return $this->redirect(
			AuthUrlCreator::userLogoutEverywhere(
				Yii::$app->id,
				'//' . Yii::$app->request->getServerName()));
	}
}

views/layouts/cabinet.php
<?php
use yii\bootstrap\BootstrapAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\web\YiiAsset;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
YiiAsset::register($this);
BootstrapAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>

<?php $this->beginBody() ?>
    <div class="wrap">
        <?php
            NavBar::begin([
                'brandLabel' => 'Личный кабинет',
                'brandUrl' => ['/cabinet/site/index'],
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => [
                    ['label' => 'Home', 'url' => ['/site/index']],
                    ['label' => 'About', 'url' => ['/site/about']],
                    ['label' => 'Contact', 'url' => ['/site/contact']],
                    Yii::$app->user->isGuest ?
                        ['label' => 'Login', 'url' => ['/site/login']] :
                        ['label' => 'Logout (' . Yii::$app->user->identity->nick . ')',
                            'url' => ['/site/logout'],
                            'linkOptions' => ['data-method' => 'post']],
                ],
            ]);
            NavBar::end();
        ?>

        <div class="container">
            <?= Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>
            <p>&nbsp;</p>
	        <p>&nbsp;</p>
	        <p>&nbsp;</p>
            <?= $content ?>
        </div>
    </div>

    <footer class="footer">
        <div class="container">
            <p class="pull-left">&copy; My Company <?= date('Y') ?></p>
            <p class="pull-right"><?= Yii::powered() ?></p>
        </div>
    </footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/empty.php
<?php
/**
 * Project: Auth - Seven lights
 * User: Evgeny Rusanov
 * E-mail: admin@dudev.ru
 * Site: dudev.ru
 */
echo $content;

views/layouts/emptyHtml.php
<?php
/**
 * Project: Auth - Seven lights
 * User: Evgeny Rusanov
 * E-mail: admin@dudev.ru
 * Site: dudev.ru
 */
use yii\helpers\Html;
/* @var $this \yii\web\View */
/* @var $content string */
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
	<meta charset="<?= Yii::$app->charset ?>"/>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?= Html::csrfMetaTags() ?>
	<title><?= Html::encode($this->title) ?></title>
	<?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<?= $content ?>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

$this->registerJsFile('//code.jquery.com/jquery-1.11.1.min.js', ['position' => \yii\web\View::POS_HEAD]);
$this->registerCssFile('/css/font-awesome.min.css');

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
	<style>
		body {
			margin: 0;
			font-family: Arial, Helvetica, Verdana, Tahoma, sans-serif;
		}
		.header {
			height: 2em;
			background-color: #333;
		}
		.header a, .header div {
			display: block;
			margin: .5em;
			color: white;
			text-decoration: none;
		}
		#sandwich, #title {
			float: left;
		}
		#envelope {
			float: right;
		}
		#menu {
			z-index: 10;
			position: absolute;
			background-color: #555;
			margin: 0;
			padding: 20px 10px;
			display: none;
		}
		#menu a {
			color: #eee;
			text-decoration: none;
			display: block;
			padding: 10px 20px;
			border-bottom: 1px solid rgba(238, 238, 238, .4);
		}
		#menu a:last-child {
			border: none;
		}
		#menu a i {
			padding-right: 15px;
		}
		#back-menu {
			height: 100%;
			width: 100%;
			position: absolute;
			margin: 0;
			opacity: 0.7;
			background-color: #000;
			display: none;
			z-index: 9;
		}
	</style>
</head>
<body>
<?php $this->beginBody() ?>
<div id="menu">
	<a href="<?= Yii::$app->urlManager->createUrl(['site/index']) ?>"><i class="fa fa-flag"></i>Тренировка</a>
	<a href="<?= Yii::$app->urlManager->createUrl(['site/rating']) ?>"><i class="fa fa-bar-chart"></i>Рейтинг</a>
	<a href="<?= Yii::$app->urlManager->createUrl(['site/dialogs']) ?>"><i class="fa fa-envelope-o"></i>Сообщения</a>
</div>
<div id="back-menu"></div>

<div class="header">
	<a class="fa fa-reorder" id="sandwich" href="#"></a>
	<div id="title"><?= Html::encode($this->title) ?></div>
	<a href="<?= Yii::$app->urlManager->createUrl(['site/dialogs']) ?>" class="fa fa-envelope-o" id="envelope"></a>
</div>
<script>
	$(document).ready(function(){
		$("#sandwich").click(showMenu);
		drawMenu();
	});
	function showMenu() {
		$("#menu").show();
		$("#back-menu")
			.show()
			.click(hideMenu);
	}
	function hideMenu() {
		$("#menu").hide();
		$("#back-menu")
			.hide()
			.unbind();
	}
	function drawMenu() {
		var menu = $("#menu");
		menu.css("min-height", "calc(100% - 40px)");
	}
</script>
<?= $content ?>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>