controllers/MessageController.php
<?php

namespace app\controllers;

use app\models\Message;
use yii\filters\AccessControl;

class MessageController extends \yii\web\Controller
{
	public function behaviors() {
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only' => ['dialog'],
				'rules' => [
					[
						'actions' => ['dialog'],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
		];
	}
    public function actionDialog($id)
    {
	    if (\Yii::$app->request->isPost) {
		    $transaction = \Yii::$app->getDb()->beginTransaction();
		    try {
			    $model = new Message();
			    $model->loadDefaultValues();
			    $model->interlocutor_id = $id;
			    $model->owner_id = \Yii::$app->user->id;
			    $model->type = 'out';
			    $model->setAttributes(\Yii::$app->request->post());
			    $model->save();

			    $model = new Message();
			    $model->loadDefaultValues();
			    $model->interlocutor_id = \Yii::$app->user->id;
			    $model->owner_id = $id;
			    $model->type = 'in';
			    $model->setAttributes(\Yii::$app->request->post());
			    $model->save();

			    $transaction->commit();
			    return $this->refresh();
		    } catch(\Exception $e) {
			    $transaction->rollBack();
		    }

	    }
        return $this->render('dialog', ['id' => $id]);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\extensions\Controller;
use app\models\AuthKey;
use app\models\User;
use general\ext\api\auth\AuthApi;
use general\ext\api\auth\AuthUrlCreator;
use Yii;
use yii\filters\AccessControl;
use yii\web\Response;

class SiteController extends Controller {
    //public $defaultAction = 'login';
	//public $layout = 'empty';
	public function behaviors() {
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only' => ['index', 'rating', 'dialogs', 'logout', 'logout-everywhere'],
				'rules' => [
					[
						'actions' => ['index', 'rating', 'dialogs', 'logout', 'logout-everywhere'],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
		];
	}
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
	public function actionIndex() {
		$this->layout = 'empty';
		return $this->render('index');
	}
	/*public function actionRating() {
		return $this->render('rating');
	}
	public function actionDialogs() {
		return $this->render('dialogs');
	}*/

	/*public function actionSignup() {
		$model = new SignupForm();
		if ($model->load(Yii::$app->request->post())) {
			if ($user = $model->signup()) {
				if (Yii::$app->user->login($user, Yii::$app->params['durationAuth'])) {
					return $this->goHome();
				}
			}
		}

		return $this->render('signup', [
			'model' => $model,
		]);
	}*/

	public function actionSignup() {
		$this->layout = 'emptyHtml';
		return $this->render('signup');
	}

    public function actionLoginWithAuthKey($result) {
	    $this->layout = 'emptyHtml';
	    if($result == 'success') {
		    if (!Yii::$app->user->isGuest) {
			    return $this->render('redirect', ['url' => '/']);
		    }

		    $mark = Yii::$app->request->get('key');
		    if($key = AuthApi::userGetServiceAuthKey($mark)) {
			    $user = User::getFromAuth($key['user_id']);

			    $model = new AuthKey();
			    $model->auth_key = $key['auth_key'];
			    $model->browser = Yii::$app->request->userAgent;
			    $model->ip = Yii::$app->request->userIP;
			    $model->user_id = $key['user_id'];
			    $model->save();

			    if (Yii::$app->user->login($user, Yii::$app->params['durationAuth'])) {
				    return $this->render('refresh');
			    }
		    } else {
			    //@todo сделать вывод ошибки
		    }
	    }
	    return $this->render('redirect', ['url' => '/']);
    }
	public function actionLoginWithMark($mark) {
		if (!Yii::$app->user->isGuest) {
			return '';
		}

		\Yii::$app->response->format = Response::FORMAT_JSONP;
		if($key = AuthApi::userGetServiceAuthKey($mark)) {
			$user = User::getFromAuth($key['user_id']);

			$model = new AuthKey();
			$model->auth_key = $key['auth_key'];
			$model->browser = Yii::$app->request->userAgent;
			$model->ip = Yii::$app->request->userIP;
			$model->user_id = $key['user_id'];
			$model->save();

			if (Yii::$app->user->login($user, Yii::$app->params['durationAuth'])) {
				return [
					'data' => 'success',
					'callback' => 'loginWithMark',
				];
			}
		}
		return [
			'data' => 'error',
			'callback' => 'loginWithMark',
		];
	}
	public function actionLogin() {
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}
		$this->layout = 'emptyHtml';
		return $this->render('login');
	}
    public function actionLogout() {
        User::logout();
	    return $this->redirect(
		    AuthUrlCreator::userLogout(
			    Yii::$app->id,
			    '//' . Yii::$app->request->getServerName()));
    }
	public function actionLogoutEverywhere() {
		User::logoutEverywhere();
		return $this->redirect(
			AuthUrlCreator::userLogoutEverywhere(
				Yii::$app->id,
				'//' . Yii::$app->request->getServerName()));
	}
}

views/site/_index.php
<?php
/* @var $this yii\web\View */
$this->title = 'Тренировка';

?>
<style>
	.marks {
		width: 100%;
		margin: 0;
	}
	#mark input {
		position: relative;
		z-index: 2;
	}
	#mark input, #mark button {
		font-size: 1.1em;
		padding: .1em;
		/* width: 100%; */
		box-sizing: border-box;
	}
	#mark button {
		/* width: 50%; */
		float: left;
	}
	.board {
		width: 100%;
		background-color: #0f610f;
		position: relative;
	}
	.task {
		background-color: #dddddd;
		padding: 0.5em;
		z-index: 2;
		margin-right: 2em;
		position: relative;
	}
	.pockets {
		width: 1.96%;
		height: 4%;
		position: absolute;
		background-color: gray;
		z-index: 1;
	}
	#pocket0 {
		width: 1.15%;
		height: 2.35%;
		border-radius: 0 0 100% 0;
	}
	#pocket1 {
		left: 49.02%;
		border-radius: 0 0 50% 50%;
		top: -2%;
	}
	#pocket2 {
		width: 1.15%;
		height: 2.35%;
		border-radius: 0 0 0 100%;
		left: 98.85%;
	}
	#pocket3 {
		width: 1.15%;
		height: 2.35%;
		border-radius: 100% 0 0 0;
		left: 98.85%;
		top: 97.65%
	}
	#pocket4 {
		left: 49.02%;
		border-radius: 50% 50% 0 0;
		top: 98%
	}
	#pocket5 {
		width: 1.15%;
		height: 2.35%;
		border-radius: 0 100% 0 0;
		top: 97.65%
	}
	.pockets.active {
		background-color: yellow;
	}
	#complexity {
		color: white;
		text-align: center;
		padding: 0.5em;
		float: right;
		font-weight: bold;
	}

	.balls {
		width: 1.96%;
		height: 4%;
		position: absolute;
		z-index: 2;
		border-radius: 50%;
	}
</style>
<div>
	<div id="complexity"></div>
	<div class="task"></div>
</div>
<div class="board">
	<div class="balls" id="ball1"></div>
	<div class="balls" id="ball2"></div>

    <div id="pocket0" class="pockets"></div>
    <div id="pocket1" class="pockets"></div>
    <div id="pocket2" class="pockets"></div>
    <div id="pocket3" class="pockets"></div>
    <div id="pocket4" class="pockets"></div>
    <div id="pocket5" class="pockets"></div>
</div>
<div class="marks">
    <form id="mark">
	    <input type="hidden" value="" id="task_id">
	    <button id="result1" type="button">1</button>
	    <button id="result3" type="button">3</button>
	    <button id="result5" type="button">5</button>
	    <button id="result10" type="button">10</button>
	    <!--input type="number" id="result" value="" min="1" placeholder="Номер удачной попытки"-->
        <button id="skip" type="button">Пропустить</button>
        <!--button id="enter" type="submit">OK</button-->
	    <style>
		    #skip {
			    width: 100%;
		    }
		    #result1, #result3, #result5, #result10 {
			    width: 25%;
			    position: relative;
			    z-index: 2;
		    }
	    </style>
    </form>
</div>




<script>
    $(document).ready(function(){
        nextTask();
        calcBoard()
    });
    /* $("#mark").submit(function() {
        nextTask();
        $(this).find("input").blur();

	    $.get("/api/task/save",
		    { task_id: $("#task_id").val(), result: $("#result").val() },
		    function(){
			    $("#result").val("");
		    }
	    );

        return false;
    }); */
    $("#result1, #result3, #result5, #result10").click(function() {
	    nextTask();
	    sendResult($(this).text());

	    return false;
    });
    function sendResult(result) {
	    $.get("/api/task/save",
		    { task_id: $("#task_id").val(), result: result }
	    );
    }
    $("#skip").click(function() {
        nextTask();
    });
    $(window).resize(function() {
        calcBoard()
    });

    function applyTask(task) {
        var ball1 = $("#ball1");
        var ball2 = $("#ball2");

        ball1.css("top", (task[0][0] * 4) + "%" );
        ball1.css("left", (task[0][1] * 1.96) + "%" );

        ball2.css("top", (task[1][0] * 4) + "%" );
        ball2.css("left", (task[1][1] * 1.96) + "%" );

	    //игровой шар
        $("#ball" + (task[4])).css("background", "radial-gradient(circle at 50% 0%, #fffff0, #fffff0 10%, #b9b9ae 80%, #8c8c83 100%)");
        $("#ball" + (task[4] + 2)).css("background", "radial-gradient(circle at 50% 0%, #fffff0, #fffff0 10%, #b9b9ae 80%, #8c8c83 100%)");
	    //биток
        $("#ball" + (task[4] + 1)).css("background", "radial-gradient(circle at 50% 0%, #ff0000, #ef0000 10%, #cc0000 80%, #9c0000 100%)");

        $(".pockets").removeClass("active");
	    $("#pocket" + task[2]).addClass("active");

	    $("#task_id").val(task[6]);

	    var $task = $(".task");
	    var $complexity = $("#complexity");

	    $task.text("Забейте \"чужой\" шар в подсвеченную лузу");

	    $complexity.text(task[5])
		    .css("background-color", "rgb(" + Math.floor(2.55 * task[5]) + ", 0, " + Math.floor(2.55 * (100 - task[5])) + ")")
		    .css("line-height", $task.height() + "px")
		    .css("min-width", $complexity.height() + "px");

	    $task.css("margin-right", $complexity.outerWidth());
    }
    function nextTask() {
	    var max = 100;
	    var min = 1;
        $.get("/api/task/get",
            { complexity: Math.floor(Math.random() * (max - min + 1)) + min },
            function(data){
                applyTask(data.tasks[0]);
            }
        );
    }
    function calcBoard() {
        var board = $(".board");
        board.height(board.width() / 2);

	    drawMenu();
    }
</script>

views/site/dialogs.php
<?php
/* @var $this yii\web\View */
use app\models\Message;
use yii\data\ActiveDataProvider;
use yii\grid\GridView;

$this->title = 'Сообщения';

$dataProvider = new ActiveDataProvider([
	'query' => Message::find()
		->where(['owner_id' => Yii::$app->user->id])
		->with('interlocutor')
		->groupBy('interlocutor_id')
		->orderBy(['created_at' => SORT_DESC]),
	'pagination' => [
		'pageSize' => 20,
	],
]);

echo GridView::widget([
	'dataProvider' => $dataProvider,
	'layout' => "{items}\n{pager}",
	'showHeader' => false,
	'columns' => [
		[
			'class' => 'yii\grid\DataColumn', // can be omitted, as it is the default
			'value' => function ($data) {
				return '<a href="' . Yii::$app->urlManager->createUrl(['message/dialog', 'id' => $data->interlocutor_id]) . '">' . $data->interlocutor->nick . '</a>';
			},
			'format' => 'raw',
		],
		[
			'class' => 'yii\grid\DataColumn', // can be omitted, as it is the default
			'value' => function ($data) {
				if($data->type == 'in' && !$data->is_read) {
					return '<a href="' . Yii::$app->urlManager->createUrl(['message/dialog', 'id' => $data->interlocutor_id]) . '" class="fa fa-envelope-o"></a>';
				}
				return '';
			},
			'format' => 'raw',
		],
	],
]);
?>
<style>
	.table {
		width: 100%;
		text-align: center;
	}
</style>

views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div id="loginForm">
    <h1><?= Html::encode($this->title) ?></h1>
    <p><?= nl2br(Html::encode($message)) ?></p>
    <p><a href="<?= Yii::$app->urlManager->createUrl('/') ?>">На главную</a></p>
</div>

views/site/index.php
<?php
/* @var $this yii\web\View */
$this->title = 'Тренировка';

?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <title>My App</title>
    <!-- Path to Framework7 Library CSS-->
    <link rel="stylesheet" href="css/framework7.ios.min.css">
    <link rel="stylesheet" href="css/framework7.ios.colors.min.css">
    <!-- Path to your custom app styles-->
    <link rel="stylesheet" href="css/my-app.css">
    <style>
        .task-wrap {
            position: relative;
            z-index: 15;
        }

        .task {
            background-color: #dddddd;
            padding: 0.5em;
            margin-right: 2em;
        }

        #complexity {
            color: white;
            text-align: center;
            padding: 0.5em;
            float: right;
            font-weight: bold;
        }

        .pockets {
            width: 1.96%;
            height: 4%;
            position: absolute;
            background-color: rgb(16, 16, 16);
            border-radius: 50%;
            box-shadow: 0 0 3px 0 rgba(0, 0, 0, 0.9);
            z-index: 20;
        }

        #pocket0 {
            top: -0.8%;
            left: -0.3%;
        }

        #pocket1 {
            top: -1.2%;
            left: 48.92%;
        }

        #pocket2 {
            top: -0.8%;
            left: 98.34%;
        }

        #pocket3 {
            top: 96.8%;
            left: 98.34%;
        }

        #pocket4 {
            top: 96.8%;
            left: 48.92%;
        }

        #pocket5 {
            top: 96.8%;
            left: -0.3%;
        }

        .pockets.active {
            background-color: yellow;
        }

        .board {
            position: absolute;
        }

        .balls {
            width: 1.96%;
            height: 4%;
            position: absolute;
            z-index: 20;
            border-radius: 50%;
        }

        #trajectory {
            width: 100%;
            height: 100%;
        }

        .marks {
            width: 100%;
            margin: 0;
            background-color: #efeff4;
            position: relative;
            z-index: 15;
        }

        #mark input {
            position: relative;
            z-index: 2;
        }

        #mark input, #mark button {
            font-size: 1.1em;
            padding: .1em;
            /* width: 100%; */
            box-sizing: border-box;
        }

        #mark button {
            /* width: 50%; */
            float: left;
        }

        #skip, #result1, #result3, #result5, #result10 {
            width: 18%;
            z-index: 2;
            display: inline-block;
            margin: 1%;
        }

        .new-message .im {
            animation-name: emergence;
            animation-duration: 1s;
            animation-iteration-count: infinite;
        }

        @keyframes emergence {
            from {
                opacity: 0;
            }
            to {
                opacity: 1;
            }
        }

        .ball-for-target {
            left: 50%;
            -webkit-transform: translate(-50%, -50%);
            -moz-transform: translate(-50%, -50%);
            -ms-transform: translate(-50%, -50%);
            -o-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);
            border-radius: 50%;
            background: radial-gradient(circle at 50% 0%, #dc0000, #ba0000 10%, #800000 80%, #640000 100%)
        }

        .ball-for-target .target {
            margin-left: 50%;
            margin-top: 50%;
            -webkit-transform: translate(-50%, -50%);
            -moz-transform: translate(-50%, -50%);
            -ms-transform: translate(-50%, -50%);
            -o-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);
        }

        .panel .menu {
            margin: 0;
        }
    </style>
    <link rel="stylesheet" href="css/font-awesome.min.css"/>
    <link rel="stylesheet" href="css/glyphicon.css">
</head>
<body>
<!-- Status bar overlay for fullscreen mode-->
<div class="statusbar-overlay"></div>
<!-- Panels overlay-->
<div class="panel-overlay"></div>
<!-- Left panel with reveal effect-->
<div class="panel panel-left panel-reveal layout-dark">
    <div class="list-block menu">
        <ul>
            <li>
                <div class="item-content">
                    <div class="item-media"><i class="glyphicon glyphicon-user"></i></div>
                    <div class="item-inner">
                        <div class="item-title"><?= Yii::$app->user->identity->nick ?></div>
                        <a href="/site/logout" class="item-link external">
                            <i class="glyphicon glyphicon-log-out"></i>
                        </a>
                    </div>
                </div>
            </li>
            <li>
                <div class="item-content">
                    <div class="item-inner"></div>
                </div>
            </li>
            <li>
                <a href="training.html" class="item-link close-panel">
                    <div class="item-content">
                        <div class="item-media"><i class="fa fa-flag"></i></div>
                        <div class="item-inner">
                            <div class="item-title">Тренировка</div>
                        </div>
                    </div>
                </a>
            </li>
            <li>
                <a href="rating.html" class="item-link close-panel">
                    <div class="item-content">
                        <div class="item-media"><i class="fa fa-bar-chart"></i></div>
                        <div class="item-inner">
                            <div class="item-title">Рейтинг</div>
                        </div>
                    </div>
                </a>
            </li>
            <li>
                <a href="dialogs.html" class="item-link close-panel">
                    <div class="item-content">
                        <div class="item-media"><i class="fa fa-envelope-o"></i></div>
                        <div class="item-inner">
                            <div class="item-title">Сообщения</div>
                        </div>
                    </div>
                </a>
            </li>
        </ul>
    </div>
</div>
<!-- Views-->
<div class="views">
    <!-- Your main view, should have "view-main" class-->
    <div class="view view-main">
        <!-- Top Navbar-->
        <div class="navbar">
            <div class="navbar-inner">
                <div class="left">
                    <a href="#" class="link icon-only open-panel"><i class="icon icon-bars"></i></a>
                </div>
                <!-- We have home navbar without left link-->
                <div class="center sliding">Загрузка</div>
                <div class="right">
                    <a href="dialogs.html" class="link"><i class="fa fa-envelope-o"></i></a>
                </div>
            </div>
        </div>
        <!-- Pages, because we need fixed-through navbar and toolbar, it has additional appropriate classes-->
        <div class="pages navbar-through toolbar-through">
            <div data-page="training" class="page">
                <div class="page-content">
                    <span style="width:42px; height:42px;margin: 10px auto 0;display: block;" class="preloader"></span>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Path to Framework7 Library JS-->
<script type="text/javascript" src="js/framework7.js"></script>
<!-- Path to your app js-->
<script type="text/javascript" src="js/my-app.js"></script>
</body>
</html>

views/site/login.php
<?php
use general\widgets\api\LoginForm;

$this->title = 'Аутентификация';
$this->params['breadcrumbs'][] = $this->title;
?>
<style>
	#login {
		border: 0 none;
		display: block;
		height: 500px;
		margin: 5% auto 0;
		width: 340px;
		max-width: 90%;
	}
</style>
<?= LoginForm::widget([
	'service' => Yii::$app->id,
	'view' => 'login',
	'retUrl' => '//' . Yii::$app->params['api']['loginUrls'][ Yii::$app->id ],
	'class' => 'login',
	'id' => 'login',
]);
?>

views/site/rating.php
<?php
/* @var $this yii\web\View */
use app\models\User;
use yii\data\ActiveDataProvider;
use yii\grid\GridView;

$this->title = 'Рейтинг';

$dataProvider = new ActiveDataProvider([
	'query' => User::find(),
	'pagination' => [
		'pageSize' => 20,
	],
]);

echo GridView::widget([
	'dataProvider' => $dataProvider,
	'layout' => "{items}\n{pager}",
	'columns' => [
		'nick',
		'rating',
		[
			'class' => 'yii\grid\DataColumn', // can be omitted, as it is the default
			'value' => function ($data) {
				return '<a href="' . Yii::$app->urlManager->createUrl(['message/dialog', 'id' => $data->id]) . '">ЛС</a>'; // $data['name'] for array data, e.g. using SqlDataProvider.
			},
			'format' => 'raw',
		],
	],
]);
?>
<style>
	.table {
		width: 100%;
		text-align: center;
	}
</style>

views/site/redirect.php
<?php
/**
 * Project: Blog Platform - Seven lights
 * User: Evgeny Rusanov
 * E-mail: admin@dudev.ru
 * Site: dudev.ru
 */
use general\controllers\api\Controller;

/* @var $url string */
?>
<script type="text/javascript">
parent.location.href= "<?= $url ?>";
</script>

views/site/refresh.php
<?php
/**
 * Project: Blog Platform - Seven lights
 * User: Evgeny Rusanov
 * E-mail: admin@dudev.ru
 * Site: dudev.ru
 */

/* @var $error int */
?>
<script type="text/javascript">
	parent.location.reload();
</script>

views/site/signup.php
<?php
use general\widgets\api\SignupForm;

$this->title = 'Регистрация';
$this->params['breadcrumbs'][] = $this->title;
?>
	<style>
		#signup {
			border: 0 none;
			display: block;
			height: 500px;
			margin: 5% auto 0;
			width: 340px;
			max-width: 90%;
		}
	</style>
<?= SignupForm::widget([
	'service' => Yii::$app->id,
	'view' => 'signup',
	'retUrl' => '//' . Yii::$app->params['api']['loginUrls'][ Yii::$app->id ],
	'class' => 'signup',
	'id' => 'signup',
]);
?>